include $(GNUSTEP_MAKEFILES)/common.make

# This is a metapackage - no actual compilation needed
PACKAGE_NAME = gershwin-components-meta

all:
	@echo "Metapackage - nothing to compile"

install:
	@echo "Metapackage - nothing to install"

clean:
	@echo "Metapackage - nothing to clean"

include $(GNUSTEP_MAKEFILES)/rules.make
